### ISSUE TITLE
Output images instead of GEXF files

### ISSUE THREAD

**Issue by greebie** [archivesunleashed/graphpass#19]
Have quickpass output image files of the plot instead of gexf.

**Comment by ianmilligan1** [comment]
Is this still a priority? Unless it's easy to do out of the box I'd recommend closing this issue - we've got graphpass working nicely with Gephi and sigma.js.

**Comment by greebie** [comment]
Yes - I have not found an image generator that does a good job of visualising. The bigger issue - dealing with large files, will require moving to a cluster-based network analyser like Snap or developing something in Spark that can handle the process.
